controllers:
    resource: ../src/Controller/
    type: attribute

company_controller:
    path: /company
    controller: App\Controller\CompanyController::loadTemplate

company_controller_add:
    path: /company/addCompany
    controller: App\Controller\CompanyController::addCompany
    methods: POST

company_controller_list:
    path: /company/listCompany
    controller: App\Controller\CompanyController::listCompany
    methods: GET

company_controller_update:
    path: /company/updateCompany/{id}
    controller: App\Controller\CompanyController::updateCompany
    methods: PUT

company_controller_delete:
    path: /company/deleteCompany/{id}
    controller: App\Controller\CompanyController::deleteCompany
    methods: DELETE

company_companyId:
    path: /company/{id}
    controller: App\Controller\CompanyController::getCompanyById
    methods: GET

company_companyName:
    path: /company/name/{name}
    controller: App\Controller\CompanyController::getCompanyByName
    methods: GET
    
company_like_companyName:
    path: /company/like/{name}
    controller: App\Controller\CompanyController::getCompanyNameLike
    methods: GET

job_controller:
    path: /job
    controller: App\Controller\JobController::loadTemplate

job_controller_add:
    path: /job/add
    controller: App\Controller\JobController::add
    methods: POST

job_controller_list:
    path: /job/list
    controller: App\Controller\JobController::list
    methods: GET

job_controller_update:
    path: /job/update/{id}
    controller: App\Controller\JobController::update
    methods: PUT

job_controller_delete:
    path: /job/delete/{id}
    controller: App\Controller\JobController::delete
    methods: DELETE

job_jobId:
    path: /job/{id}
    controller: App\Controller\JobController::getJobById
    methods: GET

job_jobName:
    path: /job/name/{name}
    controller: App\Controller\JobController::getJobByName
    methods: GET
    
job_like_jobName:
    path: /job/like/{name}
    controller: App\Controller\JobController::getJobNameLike
    methods: GET
