controllers:
    resource: ../src/Controller/
    type: attribute

company_controller:
    path: /company
    controller: App\Controller\CompanyController::loadTemplate

company_controller_add:
    path: /company/addCompany
    controller: App\Controller\CompanyController::addCompany
    methods: POST
company_controller_list:
    path: /company/listCompany
    controller: App\Controller\CompanyController::listCompany
    methods: GET

company_controller_update:
    path: /company/updateCompany/{id}
    controller: App\Controller\CompanyController::updateCompany
    methods: PUT

company_controller_delete:
    path: /company/deleteCompany/{id}
    controller: App\Controller\CompanyController::deleteCompany
    methods: DELETE
app_company_companyId:
    path: /company/{id}
    controller: App\Controller\CompanyController::companyId
    methods: GET

app_company_companyName:
    path: /company/name/{name}
    controller: App\Controller\CompanyController::companyName
    methods: GET
